scenario_info:
  name: default
  type: Custom
  description: 'Goal navigation for a training loop'
  version: '1.0'
  author: RobotSNAP
  created: '2026-10-05 11:38'
  tags: []
  map: basic/crowd
  location: ''
  dataset: null
  preview: ''
  robot_type: jackal
  duration: 0.0
points:
  robot_1_start:
    x: -7.0
    y: 0.0
    z: 0.0
    yaw: 0.0
    center: null
    size: null
  robot_1_goal:
    x: 7.0
    y: 0.0
    z: 0.0
    yaw: null
    center: null
    size: null
robots:
  - id: robot_1
    type: jackal
    start: robot_1_start
    goal: robot_1_goal
    waypoints: null
    behavior: normal
    speed: 1.5
robot: null
humans:
  - id: pedestrians
    count: 4
    spawn_window: 0.0
    spawn:
      type: random
      ref: null
      position: null
      zone:
        x: null
        y: null
        z: null
        yaw: null
        center:
          x: 0.0
          y: 0.0
          z: -5.0
        size:
          x: 3.0
          y: 0.0
          z: 3.0
      formation: scatter
      formation_parameter: 0.0
      spacing: 1.5
      relative_to: null
    goal:
      type: random
      ref: null
      position: null
      zone:
        x: null
        y: null
        z: null
        yaw: null
        center:
          x: 0.0
          y: 0.0
          z: 5.0
        size:
          x: 3.0
          y: 0.0
          z: 3.0
      formation: scatter
      formation_parameter: 0.0
      spacing: 1.5
      relative_to: null
    goals: null
    end_behavior: loop
    group: null
    movement_controller:
      type: SFM
      sfm_params: null
    behavior: normal
    speed: 1.0
    color: null
    personality: null
